name = "onedrive-index"
type = "javascript"

account_id = "fd5e01fa0a1d9e9d74a2f23e819098d8"
workers_dev = true
compatibility_date = "2024-01-01"
main = "src/pages/api/[[...routes]].ts"

[vars]
ONEDRIVE_CLIENT_ID = "df83c558-bb2b-476c-85f1-b3c7b66e556d"
ONEDRIVE_CLIENT_SECRET = "df83c558-bb2b-476c-85f1-b3c7b66e556d"
ONEDRIVE_REFRESH_TOKEN = "0.AAAAeYkvwNlMiUekGrdU3eC88gIjvSgK7GRIjuyAqt6hPeiM9vAAAJlGxRie6zRI9rscwBBA7o6w7MZoVhfjN2PtDqPkGOFXRGfT4jliByCkcmOnGckSXM71tEZrPUAhFTHmjIvjZz93SHKmWpUkzYtbFbyTRfWT
